# Generated by Django 5.2.12 on 2026-03-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_identity_memory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customermemory",
            name="memory_type",
            field=models.CharField(
                choices=[
                    ("preference", "Preference"),
                    ("past_intent", "Past Intent"),
                    ("past_project", "Past Project"),
                    ("old_objection", "Old Objection"),
                    ("prior_classification", "Prior Classification"),
                    ("support_history", "Support History"),
                    ("crm_imported", "CRM Imported"),
                    ("identity_auto_merged", "Identity Auto Merged"),
                    ("identity_manual_merged", "Identity Manual Merged"),
                    ("identity_conflict", "Identity Conflict"),
                    ("profile_updated", "Profile Updated"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="leadqualification",
            name="conversation_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="leadscore",
            name="temperature",
            field=models.CharField(
                choices=[
                    ("hot", "Hot"),
                    ("warm", "Warm"),
                    ("cold", "Cold"),
                    ("nurture", "Nurture"),
                    ("unqualified", "Unqualified"),
                    ("spam", "Spam"),
                ],
                max_length=20,
            ),
        ),
    ]
