# Generated by Django 5.2.12 on 2026-03-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_add_triage_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadscore",
            name="next_best_action",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="leadscore",
            name="journey_stage",
            field=models.CharField(
                choices=[
                    ("awareness", "Awareness"),
                    ("consideration", "Consideration"),
                    ("shortlisting", "Shortlisting"),
                    ("visit_planning", "Visit Planning"),
                    ("negotiation", "Negotiation"),
                    ("booking", "Booking"),
                    ("post_booking", "Post-Booking"),
                    ("support_retention", "Support/Retention"),
                    ("decision", "Decision"),
                    ("purchase", "Purchase"),
                    ("post_purchase", "Post-Purchase"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=50,
            ),
        ),
    ]
