# Generated by Django 5.2.12 on 2026-03-08 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrchestrationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(db_index=True, max_length=64)),
                ("intent", models.JSONField(default=dict)),
                ("qualification", models.JSONField(default=dict)),
                ("scoring", models.JSONField(default=dict)),
                ("routing", models.JSONField(default=dict)),
                ("retrieval_sources", models.JSONField(default=list)),
                ("policy_decision", models.JSONField(default=dict)),
                ("actions_triggered", models.JSONField(default=list)),
                ("next_best_action", models.CharField(blank=True, max_length=255)),
                ("response_produced", models.TextField(blank=True)),
                ("customer_type", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orchestration_snapshots",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orchestration_snapshots",
                        to="conversations.message",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResponseFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_good", models.BooleanField(default=False)),
                ("corrected_response", models.TextField(blank=True)),
                ("reason", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("created_by", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="conversations.message",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
