# Generated by Django 5.2.12 on 2026-03-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orchestrationsnapshot",
            name="escalation_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orchestrationsnapshot",
            name="journey_stage",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="orchestrationsnapshot",
            name="mode",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="orchestrationsnapshot",
            name="source_channel",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
