# Generated by Django 5.2.12 on 2026-03-09 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0002_add_snapshot_audit_fields"),
        ("conversations", "0001_initial"),
        ("leads", "0004_add_next_best_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="responsefeedback",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response_feedback",
                to="conversations.conversation",
            ),
        ),
        migrations.AddField(
            model_name="responsefeedback",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response_feedback",
                to="leads.customer",
            ),
        ),
        migrations.AddField(
            model_name="responsefeedback",
            name="issue_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="responsefeedback",
            name="mode",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
