# Generated by Django 5.2.12 on 2026-03-09 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("knowledge", "0004_structured_facts"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="companies.company",
            ),
        ),
    ]
