# Generated by hand for v0 scaffold
# Core has only abstract models - no tables created.

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = []
