# Generated by Django 5.2.12 on 2026-03-09 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
        ("leads", "0003_add_triage_fields"),
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="supportcase", name="conversation_id"),
        migrations.RemoveField(model_name="supportcase", name="customer_id"),
        migrations.AddField(
            model_name="supportcase",
            name="assigned_queue",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_cases",
                to="conversations.conversation",
            ),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="support_cases",
                to="leads.customer",
            ),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="escalation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_cases",
                to="support.escalation",
            ),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="escalation_trigger",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("critical", "Critical"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="sla_bucket",
            field=models.CharField(
                blank=True,
                choices=[
                    ("p1", "P1 (2h)"),
                    ("p2", "P2 (8h)"),
                    ("p3", "P3 (24h)"),
                    ("p4", "P4 (72h)"),
                ],
                default="p3",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="supportcase",
            name="category",
            field=models.CharField(
                choices=[
                    ("installment", "Installment"),
                    ("contract", "Contract"),
                    ("maintenance", "Maintenance"),
                    ("delivery", "Delivery"),
                    ("handover", "Handover"),
                    ("complaint", "Complaint"),
                    ("documentation", "Documentation"),
                    ("general_support", "General Support"),
                    ("after_sale", "After-Sale"),
                    ("warranty", "Warranty"),
                    ("payment", "Payment"),
                    ("payment_proof", "Payment Proof"),
                    ("general", "General"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="supportcase",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("pending_customer", "Pending Customer"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=50,
            ),
        ),
    ]
