# Generated by Django 5.2.12 on 2026-03-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_add_triage_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="escalation",
            name="handoff_summary",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="escalation",
            name="reason",
            field=models.CharField(
                choices=[
                    ("angry_customer", "Angry Customer"),
                    ("legal_contract", "Legal/Contract Issue"),
                    ("pricing_exception", "Pricing Exception"),
                    ("unavailable_critical_info", "Unavailable Critical Info"),
                    ("low_confidence", "Low Confidence"),
                    ("vip_lead", "VIP Lead"),
                    ("severe_complaint", "Severe Complaint"),
                    ("negotiation_beyond_policy", "Negotiation Beyond Policy"),
                    ("pricing_request", "Pricing Request"),
                    ("complex_inquiry", "Complex Inquiry"),
                    ("complaint", "Complaint"),
                    ("urgent", "Urgent"),
                    ("vip", "VIP"),
                    ("manual", "Manual"),
                ],
                max_length=50,
            ),
        ),
    ]
