# Generated by Django 5.2.12 on 2026-03-09 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
        ("conversations", "0001_initial"),
        ("leads", "0004_add_next_best_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="humancorrection",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="human_corrections",
                to="conversations.conversation",
            ),
        ),
        migrations.AddField(
            model_name="humancorrection",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="human_corrections",
                to="leads.customer",
            ),
        ),
        migrations.AddField(
            model_name="humancorrection",
            name="is_correct",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="humancorrection",
            name="issue_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="humancorrection",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="human_corrections",
                to="conversations.message",
            ),
        ),
        migrations.AddField(
            model_name="humancorrection",
            name="mode",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("message_processed", "Message Processed"),
                    ("lead_scored", "Lead Scored"),
                    ("orchestration_started", "Orchestration Started"),
                    ("orchestration_stage", "Orchestration Stage"),
                    ("orchestration_completed", "Orchestration Completed"),
                    ("orchestration_failed", "Orchestration Failed"),
                    ("escalation_created", "Escalation Created"),
                    ("escalation_resolved", "Escalation Resolved"),
                    ("correction_applied", "Correction Applied"),
                    ("crm_imported", "CRM Imported"),
                    ("knowledge_ingested", "Knowledge Ingested"),
                    ("knowledge_reindexed", "Knowledge Reindexed"),
                    ("knowledge_verified", "Knowledge Verified"),
                    ("identity_auto_merged", "Identity Auto Merged"),
                    ("identity_manual_merged", "Identity Manual Merged"),
                    ("identity_conflict", "Identity Conflict"),
                    ("profile_updated", "Profile Updated"),
                ],
                max_length=50,
            ),
        ),
    ]
