# Generated by Django 5.2.12 on 2026-03-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_humancorrection_sales_linkage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("message_processed", "Message Processed"),
                    ("lead_scored", "Lead Scored"),
                    ("orchestration_started", "Orchestration Started"),
                    ("orchestration_stage", "Orchestration Stage"),
                    ("orchestration_completed", "Orchestration Completed"),
                    ("orchestration_failed", "Orchestration Failed"),
                    ("escalation_created", "Escalation Created"),
                    ("escalation_resolved", "Escalation Resolved"),
                    ("correction_applied", "Correction Applied"),
                    ("crm_imported", "CRM Imported"),
                    ("knowledge_ingested", "Knowledge Ingested"),
                    ("knowledge_reindexed", "Knowledge Reindexed"),
                    ("knowledge_reparsed", "Knowledge Reparsed from file"),
                    ("knowledge_verified", "Knowledge Verified"),
                    ("identity_auto_merged", "Identity Auto Merged"),
                    ("identity_manual_merged", "Identity Manual Merged"),
                    ("identity_conflict", "Identity Conflict"),
                    ("profile_updated", "Profile Updated"),
                ],
                max_length=50,
            ),
        ),
    ]
