# Generated by Django 5.2.12 on 2026-03-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=80, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("logo_url", models.URLField(blank=True)),
                (
                    "primary_color",
                    models.CharField(
                        blank=True, help_text="Hex e.g. #1a365d", max_length=20
                    ),
                ),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("support_phone", models.CharField(blank=True, max_length=50)),
                ("website_url", models.URLField(blank=True)),
                (
                    "contact_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra contact info: address, social links, etc.",
                    ),
                ),
                (
                    "tone_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="formality, default_lang, escalation_preferences, etc.",
                    ),
                ),
                (
                    "default_channel_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="enabled_channels, default_channel, channel_config per channel",
                    ),
                ),
                (
                    "knowledge_namespace",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Namespace for knowledge partitioning; blank = default",
                        max_length=100,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
    ]
